## Code generator for the fixed-arity nn<K> entry points, K = 1..KMAX.
## Emits  src/nnEvalGen.c  (C scalar entry points + rxode2 registration) and
##        R/nnGen.R        (R wrappers + translation-table rows + rxD chains).
## Run from the package root:  Rscript tools/genNn.R
KMAX <- 4L

.args <- function(K) paste0("double x", seq_len(K))
.names <- function(K) {
  fwd <- sprintf("nn%d", K)
  d1  <- if (K >= 1) sprintf("nn%d_d%d", K, seq_len(K)) else character(0)
  d2  <- character(0)
  for (j in seq_len(K)) for (l in j:K) d2 <- c(d2, sprintf("nn%d_d%d_d%d", K, j, l))
  list(fwd = fwd, d1 = d1, d2 = d2, all = c(fwd, d1, d2))
}

## ---- C file -------------------------------------------------------------
cC <- c(
  "/* GENERATED by tools/genNn.R -- do not edit by hand.",
  "   Fixed-arity rxode2 entry points nn<K> / nn<K>_d<j> / nn<K>_d<j>_d<l>",
  paste0("   (K = 1..", KMAX, "); each calls nnForward/nnGrad/nnHess in nnEval.c. */"),
  "#include <stdint.h>",
  "#include <R.h>",
  "#include <Rinternals.h>",
  "#include <R_ext/Rdynload.h>",
  "#include <rxode2parseStruct.h>",
  "#include \"nlmixr2nn.h\"",
  "")
cReg <- c("void nnRegisterCallables(void) {")
for (K in seq_len(KMAX)) {
  a <- paste(c("double id", .args(K)), collapse = ", ")
  xi <- paste0("  double x[", K, "] = {", paste0("x", seq_len(K), collapse = ", "), "};")
  cC <- c(cC, sprintf("double nn%d(%s) {", K, a), xi,
          "  return nnForward((int) id, x);", "}")
  for (j in seq_len(K)) {
    cC <- c(cC, sprintf("double nn%d_d%d(%s) {", K, j, a), xi,
            sprintf("  return nnGrad((int) id, x, %d);", j - 1L), "}")
  }
  for (j in seq_len(K)) for (l in j:K) {
    cC <- c(cC, sprintf("double nn%d_d%d_d%d(%s) {", K, j, l, a), xi,
            sprintf("  return nnHess((int) id, x, %d, %d);", j - 1L, l - 1L), "}")
  }
  for (nm in .names(K)$all) {
    cReg <- c(cReg, sprintf("  R_RegisterCCallable(\"nlmixr2nn\", \"%s\", (DL_FUNC) &%s);", nm, nm))
  }
}
cC <- c(cC, "", cReg, "}", "")
writeLines(cC, "src/nnEvalGen.c")

## ---- R file -------------------------------------------------------------
rR <- c(
  "## GENERATED by tools/genNn.R -- do not edit by hand.",
  "## R wrappers (needed by rxode2's symengine reverse renderer, and for direct",
  "## evaluation), the translation-table rows, and the rxD derivative chains for",
  paste0("## the nn<K> family (K = 1..", KMAX, ")."),
  "")
## R wrapper functions
for (K in seq_len(KMAX)) {
  a <- paste(c("id", .args(K)), collapse = ", ")  # x1.. bare in formals
  a <- paste(c("id", paste0("x", seq_len(K))), collapse = ", ")
  xs <- paste0("x", seq_len(K), collapse = ", ")
  rR <- c(rR, sprintf("nn%d <- function(%s) .nnEvalR(id, 0L, 0L, 0L, %s)", K, a, xs))
  for (j in seq_len(K)) {
    rR <- c(rR, sprintf("nn%d_d%d <- function(%s) .nnEvalR(id, 1L, %dL, 0L, %s)",
                        K, j, a, j - 1L, xs))
  }
  for (j in seq_len(K)) for (l in j:K) {
    rR <- c(rR, sprintf("nn%d_d%d_d%d <- function(%s) .nnEvalR(id, 2L, %dL, %dL, %s)",
                        K, j, l, a, j - 1L, l - 1L, xs))
  }
}
## translation-table rows
allNames <- character(0); allNargs <- integer(0)
for (K in seq_len(KMAX)) {
  nm <- .names(K)$all
  allNames <- c(allNames, nm)
  allNargs <- c(allNargs, rep(K + 1L, length(nm)))  # +1 for the id argument
}
rR <- c(rR, "",
        ".nnGenNames <- c(", paste0("  ", paste0("\"", allNames, "\"", collapse = ", ")), ")",
        ".nnGenNargs <- c(", paste0("  ", paste(allNargs, collapse = ", ")), ")")
## rxD chains.  Each derivative-generating function returns the C-expression
## string for the derivative call, e.g.
##   function(id, x1, x2) paste0("nn2_d1(", id, ",", x1, ",", x2, ")")
argstr <- function(K) paste0("x", seq_len(K))
mkDerivFn <- function(target, K) {
  a <- c("id", argstr(K))
  body <- paste0('paste0("', target, '(", ', paste(a, collapse = ', ",", '), ', ")")')
  paste0("function(", paste(a, collapse = ", "), ") ", body)
}
rR <- c(rR, "", ".nnGenRegisterD <- function() {")
for (K in seq_len(KMAX)) {
  ## nn<K>: d/d id = NULL, d/d x_j -> nn<K>_d<j>(...)
  entries <- c("NULL", vapply(seq_len(K),
    function(j) mkDerivFn(sprintf("nn%d_d%d", K, j), K), character(1)))
  rR <- c(rR, sprintf("  rxD(\"nn%d\", list(%s))", K, paste(entries, collapse = ", ")))
  ## nn<K>_d<j>: d/d x_l -> nn<K>_d<min>_d<max>(...) (symmetric)
  for (j in seq_len(K)) {
    e2 <- c("NULL", vapply(seq_len(K),
      function(l) mkDerivFn(sprintf("nn%d_d%d_d%d", K, min(j, l), max(j, l)), K),
      character(1)))
    rR <- c(rR, sprintf("  rxD(\"nn%d_d%d\", list(%s))", K, j, paste(e2, collapse = ", ")))
  }
}
rR <- c(rR, "  invisible()", "}")
writeLines(rR, "R/nnGen.R")

cat("generated src/nnEvalGen.c and R/nnGen.R for K=1..", KMAX, "\n", sep = "")
cat("nn function names:\n"); print(allNames)
