## R interface to the C++ libtorch backend (src/nnTorch.cpp).  The torch modules
## live entirely in C++ so they are reachable from compiled solve/objective code
## without calling back into R; these wrappers only drive setup, sync, and
## save/restore from the main thread.

## `.nnEnv$torchIds` (attached module ids) is initialized in aaa.R.

#' Create a C++ torch module for a network
#'
#' @param id network id.
#' @param K input dimension.
#' @param H hidden width.
#' @param act activation ("relu", "softplus", "tanh").
#' @param seed optional integer seed for weight initialization.
#' @return invisibly, the id.
#' @export
nnTorchInit <- function(id, K, H, act = "relu", seed = NULL) {
  act <- match.arg(tolower(act), names(.nnActCode))
  .Call(`_nlmixr2nn_nnTorchInit`, as.integer(id), as.integer(K), as.integer(H),
        .nnActCode[[act]], if (is.null(seed)) NULL else as.integer(seed))
  .nnEnv$torchIds <- union(.nnEnv$torchIds, as.integer(id))
  invisible(as.integer(id))
}

#' Push a torch module's weights into the loader buffer (C path, no R round-trip)
#' @param id network id.
#' @return invisibly, the number of weights synced.
#' @export
nnTorchSync <- function(id) invisible(.Call(`_nlmixr2nn_nnTorchSync`, as.integer(id)))

#' Flat weights of a torch module (nnWeightLayout order)
#' @param id network id.
#' @return numeric vector.
#' @export
nnTorchWeights <- function(id) .Call(`_nlmixr2nn_nnTorchGetWeights`, as.integer(id))

#' Load flat weights into a torch module
#' @param id network id.
#' @param values numeric weight vector.
#' @return invisibly NULL.
#' @export
nnTorchSetWeights <- function(id, values) {
  invisible(.Call(`_nlmixr2nn_nnTorchSetWeights`, as.integer(id), as.double(values)))
}

#' Forward pass of a torch module at one input (for validation)
#' @param id network id.
#' @param x numeric input vector of length K.
#' @return numeric scalar.
#' @export
nnTorchForward <- function(id, x) .Call(`_nlmixr2nn_nnTorchForward`, as.integer(id), as.double(x))

#' Free a torch module
#' @param id network id.
#' @return invisibly NULL.
#' @export
nnTorchFree <- function(id) {
  .Call(`_nlmixr2nn_nnTorchFree`, as.integer(id))
  .nnEnv$torchIds <- setdiff(.nnEnv$torchIds, as.integer(id))
  invisible()
}

#' Save / load a trained torch module to a binary
#'
#' @param id network id.
#' @param file path to the serialized module.
#' @return invisibly NULL.
#' @export
nnTorchSave <- function(id, file) invisible(.Call(`_nlmixr2nn_nnTorchSave`, as.integer(id), file))

#' @rdname nnTorchSave
#' @export
nnTorchLoad <- function(id, file) invisible(.Call(`_nlmixr2nn_nnTorchLoad`, as.integer(id), file))

#' Create C++ torch modules for all networks in a model
#'
#' For each network generated by [nn()] in an assembled model, creates a C++
#' torch module of the recorded shape.  Weights reach the solve via
#' [nnUpdate()], which syncs each attached module into the loader buffer.
#'
#' @param x an assembled rxode2 model / ui object built with [nn()].
#' @param seed optional integer seed for reproducible initialization.
#' @return invisibly, a data.frame of the created modules.
#' @export
nnTorchModel <- function(x, seed = NULL) {
  reg <- .nnEnv$reg
  if (length(reg) == 0L) {
    stop("no nn() networks registered; build a model with nn() first", call. = FALSE)
  }
  info <- lapply(reg, function(m) {
    nnTorchInit(m$id, m$K, m$H, m$act,
                seed = if (is.null(seed)) NULL else seed + m$id)
    data.frame(id = m$id, K = m$K, H = m$H, act = m$act)
  })
  invisible(do.call(rbind, info))
}
